### ISSUE TITLE
Can you add before and after pagination

### ISSUE THREAD

**Issue by THM068** [gavanitrate/faunadb-http-dart#1]
Hi dude,
Thank you so much for creating the dart fauna db client. It looks good and I have been playing around with it.
I want to create a flutter app that directly communicate with fauna. 

May you kindly add pagination with the before and after flag. At the moment it only supports size.

Thanks in advance, :)

**Comment by gavanitrate** [comment]
Hey man, I'm glad you like the library so far.
I am working on adding pagination, I will try to push something in the next few days.

**Comment by gavanitrate** [comment]
I pushed a new version of the library recently. Let me know if it works out for you 👍
