### ISSUE TITLE
Join query doesn't work

### ISSUE THREAD

**Issue by ammarhemani** [gavanitrate/faunadb-http-dart#11]
Hi, 
First of all, thank you for creating this package, it's really helping me out! 
Now to the problem:

**Query in Flutter:**
```
Paginate(
Join(
       Match(Index("conversations_by_receiver_id"), terms: [Ref(Collection("users"), "291258025493135872")]), 
       Index("messages_by_conversation")
       )
)
```

This query when run in Flutter, gives the error:
`{"errors":[{"position":["paginate"],"code":"invalid expression","description":"No form/function found, or invalid argument keys: { join, detail }."}]}`

Whereas, if I run the same query on the Fauna Shell (after converting the named parameters to positional), it works flawlessly.

**Query on Fauna Shell:** 
```
Paginate(
  Join(
    Match(Index("conversations_by_receiver_id"), Ref(Collection("users"), "291258025493135872")),
    Index("messages_by_conversation"),
  )
)
```

I tried searching around but couldn't find what the issue is. Can you help?

Thanks! 

Ammar

**Comment by gavanitrate** [comment]
Hey, thanks for uncovering this bug! This should be fixed in 0.9.1 - just pushed that now 🎉
