### ISSUE TITLE
Ref.fromJson doesn't work

### ISSUE THREAD

**Issue by ammarhemani** [gavanitrate/faunadb-http-dart#12]
Hello there,
I was working with your package and couldn't find a way to convert a Ref object back to the way that it's stored in Fauna. 

By default this is the Ref Object fauna creates:
```
Ref(Collection("messages"), "292355481851134470"),
```
This is what I get when I do Ref.toJson() from your package:
```
{"ref":{"collection":"users"},"id":"290805807859106306"}
```

Can you help, please? 

Thanks!

**Comment by gavanitrate** [comment]
hey! so what you get back from the server is not the same as the as a `Ref`, it is a `RefResult`. this class has a helper object to convert this class back to a Ref that can be used in a subsequent query. here is an example of how to get a Ref from a RefResult.
```
import 'package:faunadb_http/faunadb_http.dart';
import 'package:faunadb_http/query.dart';

void main(List<String> arguments) async {
  final config = FaunaConfig.build(
    secret: arguments[0],
  );
  final client = FaunaClient(config);

  final refQuery = Ref(Collection('users'), '284854841250939405');
  final refResponse = await client.query(refQuery);
  final refResult = refResponse.resource as RefResult;
  final refFromRefResult = refResult.asRef();

  final getQuery = Get(refFromRefResult);
  final response = await client.query(getQuery);
  print(response.resource);

  client.close();
}
```
does this help with your goal?
