### ISSUE TITLE
Range Function

### ISSUE THREAD

**Issue by hasimyerlikaya** [gavanitrate/faunadb-http-dart#15]
Hi,

It seems that there is no Range function.
If not, is it possible to add it?

Thank you.

**Comment by hasimyerlikaya** [comment]
Can you tell me if you can add this function or not?
I'm sure you have a lot of work, but I need it a little urgently, I would be glad if you could help :)

**Comment by gavanitrate** [comment]
I will push a new version with this very soon.

**Comment by gavanitrate** [comment]
has been added in v0.11.0. i will try to add a PR guide soon so people can contribute in a consistent fashion.

**Comment by hasimyerlikaya** [comment]
Thank you so much.

I thought of doing it myself, but I couldn't because I didn't know the system.
If it becomes a Pull Request Guide, we can add it ourselves when necessary.

Thank you again.
