### ISSUE TITLE
Query: Issue in writing createfunction

### ISSUE THREAD

**Issue by CoderJerry** [gavanitrate/faunadb-http-dart#19]
I am trying to convert this [sample app example](https://github.com/fauna-brecht/fwitter) into flutter code.

to understand the concept better I am trying to keep the folder structure and code structure as same as given in this sample app.
and when I am trying to do database setup as done in this example where a UDF is created from js code to handle email and password login

(src/setup/database.js)

`await handleSetupError(client.query(CreateLoginUDF), 'user defined function - login')`

(src/setup/functions.js)

`const CreateLoginUDF = CreateOrUpdateFunction({
  name: 'login',
  body: Query(Lambda(['email', 'password'], LoginAccount(Var('email'), Var('password')))),
  role: Role('functionrole_login')
})`

(src/queries/auth.js)

```
function LoginAccount(email, password) {
  const FQLStatement = If(
    Identify(Match(Index('accounts_by_email'), email), password),
    Do(
      Let(
        {
          rateLimitingPage: Paginate(Match(Index('rate_limiting_by_action_and_identity'), 'login', email))
        },
        If(
          // Check whether there is a value
          IsEmpty(Var('rateLimitingPage')),
          true,
          Delete(Select([0], Var('rateLimitingPage')))
        )
      ),
      // Just login as usual so we get the same result we had before.
      LoginAccountExample2(email, password)
    ),
    // If unsuccesfull.. we don't need to do anything special, just return false is fine.
    false
  )

  // And of course we want to add rate-limiting first.
  // The rate limiting config for login contains calls: 3 and perSeconds: 0 (see './rate-limiting.js)
  // 0 means that there is no decay, no matter how long you wait you can do maximum 3 calls.
  // But on successful login we clean up the rate-limiting so they only remain on failed logins.
  const query = AddRateLimiting('login', FQLStatement, email)
  return query
}
```

I got the CreateLoginUDF js function to below dart function

`class FunctionHelper {
  static Expr get createLoginUDF => CreateFunction(
        Obj({
          'name': 'login',
          'body': Query(Lambda(['email', 'password'],
              AuthHelper.loginAccount(Var('email'), Var('password')))),
          'role': Role('functionrole_login')
        }),
      );
}`

but when I am trying to convert LoginAccount js function (src/queries/auth.js) to dart code like 

`class AuthHelper {
  static loginAccount(Expr email, Expr password) {
    final fql = If(
        Identify(Match(Index('accounts_by_email'), terms: [email]),
            password),
        Do([
          Let(
              {
                'rateLimitingPage': Paginate(Match(
                    Index('rate_limiting_by_action_and_identity'),
                    terms: ['login', email]))
              },
              If(
                  // Check whether there is a value
                  IsEmpty(Var('rateLimitingPage')),
                  true,
                  Delete(Select([0], Var('rateLimitingPage'))))),
          // Just login as usual so we get the same result we had before.
          LoginAccountExample2(email, password),
        ]),
        // If unsuccesfull..
        // we don't need to do anything special, just return false is fine.
        false);
    const query = addRateLimiting('login', fql, email);
    return query;
  }
}`

I m getting this compiler issue:
The argument type 'Match' can't be assigned to the parameter type 'Ref'.
`The argument type 'Expr' can't be assigned to the parameter type 'String'.`

I got confused and stuck when loginAccount function takes Expr as arguments for email and password from its caller FunctionHelper.createLoginUDF but Identify expects String to be passed as password in dart code. 

and will it be okey to cast 
Match(Index('accounts_by_email'), terms: [email]) as Ref
to remove The argument type 'Match' can't be assigned to the parameter type 'Ref'.

how to get over this issue?

**Comment by gavanitrate** [comment]
i think i know this is a bug, i will be able to sort it out soon. it's basically a type mismatch. moving forward, everything will probably just accept an Object, so you can pass in whatever data type. i will try to fix this soon, but i don't think i can for a day or two.

**Comment by gavanitrate** [comment]
i have pushed version 0.13.1. this should fix the `The argument type 'Match' can't be assigned to the parameter type 'Ref'` error. i believe the other error is occurring because loginAccount function expects `email` to be `Expr`; just change this to `String`.
