### ISSUE TITLE
Request to add Ref in create collection

### ISSUE THREAD

**Issue by THM068** [gavanitrate/faunadb-http-dart#2]
Hi Dude, 
Me again. Can you add ref when adding a object to a collection. I would like to use my own Id for the document and 
also to add the id to the actual document I am creating. It is easy to retrieve the data block with an id already .

Like so 

> serverClient.query(
  q.Create(
    q.Ref(q.Collection('posts'), '1'),
    { data: { title: 'The first post' } },
  )
)
.then((ret) => console.log(ret))

Thanks in advance

**Comment by gavanitrate** [comment]
Thanks for the feedback man! Keep making issues for any functionality you want 👌
Just pushed version 0.6.0 - that should fix this 👍
