### ISSUE TITLE
Can you add support for region groups in your dart client

### ISSUE THREAD

**Issue by THM068** [gavanitrate/faunadb-http-dart#23]
I saw that fauna is now using region groups to create data in particular regions e.g US, UK etc to comply with GDPR rules. Can you add it to your client so that we can have a choice on where are our data will be stored.
https://fauna.com/blog/meeting-data-residence-and-increasing-performance-with-fauna-region-groups

**Comment by gavanitrate** [comment]
According to [this](https://docs.fauna.com/fauna/current/api/fql/region_groups), you can choose your region group by connecting to the correct connection domain. You should be able to connect to the EU region group by building a `FaunaConfig` like this.
```
final config = FaunaConfig.build(
  secret: <secret>,
  domain: 'db.eu.fauna.com'
);
```
Let me know if you have any issues.
