### ISSUE TITLE
What is the reason for this library being called a long name such as `faunadb-http-dart` instead of `fauna-dart` or simply `fauna`?

### ISSUE THREAD

**Issue by vxern** [gavanitrate/faunadb-http-dart#24]

**Comment by gavanitrate** [comment]
😂 That's a good point. I didn't really plan to release this publicly from the start so I didn't plan things out too much. I was hoping the team at Fauna would release an official Dart driver at some point, and I wanted to leave the most 'convenient' library name available to them.
