### ISSUE TITLE
Unable to get a default value on Select using the package

### ISSUE THREAD

**Issue by rahul-rakesh** [gavanitrate/faunadb-http-dart#27]
Could you please help me with this query. Not sure where to reach out to someone to get some insights on this.
https://stackoverflow.com/questions/69966125/fauna-db-and-flutter-unable-to-get-a-default-value-on-select-using-the-faunadb

**Comment by gavanitrate** [comment]
Hey, so you want to return a String as the result from Select if the specified key doesn't exist? Am I understanding that correctly?

**Comment by gavanitrate** [comment]
I have just pushed a new version `0.13.4`. Please try this out.

**Comment by rahul-rakesh** [comment]
Thanks for the lightening fast resolution. Its working.
