### ISSUE TITLE
The argument can be optional when calling functions

### ISSUE THREAD

**Issue by hasimyerlikaya** [gavanitrate/faunadb-http-dart#5]
Hi,
Thank you for this package.

I'm running a query like this.

`final query = Call(Function_("all_letters_func"), null);`

The function I created does not take any parameters.
But since it is mandatory here, I have to send it as null. Functions can be called without taking parameters.
Therefore, you can make it optional.

The fauna can be called from the shell as follows;

`Call(Function("all_letters_func"))`

**Comment by gavanitrate** [comment]
thanks for the feedback. this should be updated in the latest version 0.8.1.
